version: '3'

services:
  app:
    container_name: user_comments_api
    image: user-comments-api-service:1.0.0
    build:
      dockerfile: ./Dockerfile
      context: ./
      args:
        NODE_ENV: development
    command: npm run dev
    ports:
      - 3000:3000
    env_file:
      - .env
    networks:
      - express-network
    volumes:
      - .:/usr/src/app

networks:
  express-network:
    driver: bridge